[package]
name = "st_egano"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.7"

# Special config for the binary because src dir is called Quelltext and not src
[[bin]]
name = "st_egano"
path = "Quelltext/main.rs"
